### ISSUE TITLE
Alternative names for values.yml

### ISSUE THREAD

**Issue by muffinhydra** [Nestsiarenka/helm-template-preview-and-more#7]
Hello! 

For a current project I am working its neccesary to use different values.yaml file names in the format for example:

minikube-values.yaml
rancher-values.yaml
...

within the same chart. The correct values.yaml ist then loaded with an argument in the console command. 

Sadly the preview only works with the values.yaml file name not with alrenative ones. 

Would it be possible to add configuration for different values.yaml file names similar to the Helm intellisense one? 
![MicrosoftTeams-image](https://github.com/Nestsiarenka/helm-template-preview-and-more/assets/82774354/367807a2-6143-42ab-b39a-e043f545ad1f)

**Comment by Nestsiarenka** [comment]
Hello!

Thank you for the input. I think it's a good feature and I'm going to implement this probably this week.

Just in case, to clarify the expected behaviour:
1. Files from the list if found are "combined" and applied like if everything was in the single `values.yaml`
2. If file is not found it's just ignored
3. The higher file has precedence over the lower files. So in case of conflicts, values of the higher file will be applied.

**Comment by Nestsiarenka** [comment]
Hello! New version (v1.2.0) has been released with the discussed feature onboarded. 

Please, give it a try. Looking forward for your feedback.
